const actionType = {
    FETCH_BANKS: 'FETCH_BANKS',
    SELECT_BANK: 'SELECT_BANK',
    CLEAR_SELECTED: 'CLEAR_SELECTED',
    LOADING: 'LOADING',
    INITIATE_TRANSFER: 'INITIATE_TRANSFER',
    FINALIZE_TRANSFER: 'FINALIZE_TRANSFER',
    FETCH_TRANSFERS: 'FETCH_TRANSFERS'
};

export default actionType;